---
name: Auto-deployment of datalab_schema Documentation
on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Install cached uv
        uses: hynek/setup-cached-uv@v2

      - name: Install dependencies
        run: |
          uv venv
          uv pip install '.[dev]'

      - name: Build documentation.
        run: |
          source .venv/bin/activate
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          make mkd-gh-deploy
