# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
---
name: Build and test datalab_schema

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install cached uv
        uses: hynek/setup-cached-uv@v2

      - name: Install dependencies
        run: |
          uv venv
          uv pip install '.[dev]'

      - name: Run test suite
        run: make test
