name: Preview datalab_schema documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install cached uv
        uses: hynek/setup-cached-uv@v2

      - name: Install dependencies
        run: |
          uv venv
          uv pip install '.[dev]'

      - name: Build documentation.
        run: |
          source .venv/bin/activate
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          make mkd-gh-deploy
          mkdocs build -d site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/
          preview-branch: gh-pages
